export const data = [
	{
		id: 1,
		img: 'https://i.postimg.cc/yNHnPss8/hoodie-travis.png',
		nameProduct: 'HOODIE TRAVIS OVERSIZE',
		price: 18760,
		quantity: 1,
		category: 'hoodie',
	},
	{
		id: 2,
		img: 'https://i.postimg.cc/hj4rksJF/pegaso.png',
		nameProduct: 'PEGASO',
		price: 11200,
		quantity: 1,
		category: 'remeras',
	},
	{
		id: 3,
		img: 'https://i.postimg.cc/pdJCc4LY/moon.png',
		nameProduct: 'MOON',
		price: 11200,
		quantity: 1,
		category: 'remeras',
	},
	{
		id: 4,
		img: 'https://i.postimg.cc/3xpnmdMq/poseidon.png',
		nameProduct: 'POSEIDON',
		price: 11200,
		quantity: 6,
		category: 'remeras',
	},
	{
		id: 5,
		img: 'https://i.postimg.cc/L6GxJjWf/hoodie-butterfly.jpg',
		nameProduct: 'HOODIE BUTTERFLY RAY X',
		price: 25999,
		quantity: 1,
		category: 'hoodie',
	},
	{
		id: 6,
		img: '',
		nameProduct: '',
		price: 0,
		quantity: 1,
		category: '',
	},
	{
		id: 7,
		img: '',
		nameProduct: '',
		price: 0,
		quantity: 1,
		category: '',
	},
	{
		id: 8,
		img: '',
		nameProduct: '',
		price: 0,
		quantity: 1,
		category: '',
	},
	{
		id: 9,
		img: '',
		nameProduct: '',
		price: 0,
		quantity: 1,
		category: '',
	},
	{
		id: 10,
		img: '',
		nameProduct: '',
		price: 0,
		quantity: 1,
		category: '',
	},
	{
		id: 11,
		img: '',
		nameProduct: '',
		price: 0,
		quantity: 1,
		category: '',
	},
];
