export const data = [
	{
		id: 1,
		img: 'https://i.postimg.cc/yNHnPss8/hoodie-travis.png',
		nameProduct: 'HOODIE TRAVIS OVERSIZE',
		price: 18760,
		quantity: 1,
		category: 'hoodie',
	},
	{
		id: 2,
		img: 'https://i.postimg.cc/hj4rksJF/pegaso.png',
		nameProduct: 'PEGASO',
		price: 11200,
		quantity: 1,
		category: 'remeras',
	},
	{
		id: 3,
		img: 'https://i.postimg.cc/pdJCc4LY/moon.png',
		nameProduct: 'MOON',
		price: 11200,
		quantity: 1,
		category: 'remeras',
	},
	{
		id: 4,
		img: 'https://i.postimg.cc/3xpnmdMq/poseidon.png',
		nameProduct: 'POSEIDON',
		price: 11200,
		quantity: 6,
		category: 'remeras',
	},
	{
		id: 5,
		img: 'https://i.postimg.cc/L6GxJjWf/hoodie-butterfly.jpg',
		nameProduct: 'HOODIE BUTTERFLY RAY X',
		price: 25999,
		quantity: 1,
		category: 'hoodie',
	},
	{
		id: 6,
		img: 'https://i.postimg.cc/Gh4M3XXd/ray-negra.webp',
		nameProduct: 'DELIRA RAY NEGRA',
		price: 10800,
		quantity: 1,
		category: 'remeras',
	},
	{
		id: 7,
		img: 'https://i.postimg.cc/jSFzXRFY/gorra-volcon.png',
		nameProduct: 'GORRA RIPCURL GRAY',
		price: 7500,
		quantity: 1,
		category: 'gorras',
	},
	{
		id: 8,
		img: 'https://i.postimg.cc/g2pj5N5P/try-other-espalda-crema-fresh1-7798bf390b1e4d3aa116820441015293-480-0.webp',
		nameProduct: 'TRY OTHER CREAM',
		price: 10800,
		quantity: 1,
		category: 'remeras',
	},
	{
		id: 9,
		img: '',
		nameProduct: '',
		price: 0,
		quantity: 1,
		category: '',
	},
	{
		id: 10,
		img: '',
		nameProduct: '',
		price: 0,
		quantity: 1,
		category: '',
	},
	{
		id: 11,
		img: '',
		nameProduct: '',
		price: 0,
		quantity: 1,
		category: '',
	},
];
